from fastapi import FastAPI, HTTPException, UploadFile, File, Form
from pydantic import BaseModel
from langchain_core.messages import HumanMessage
import uuid

from ChatBotRAG_backend import chatbot, ingest_pdf


app = FastAPI()


# =========================
# Request Model
# =========================

class ChatRequest(BaseModel):
    question: str
    videoId: str | None = None
    threadId: str | None = None


# =========================
# Health Check
# =========================

@app.get("/")
def root():
    return {
        "message": "AI service is running"
    }


# =========================
# Chat Endpoint
# =========================

@app.post("/chat")
def chat(request: ChatRequest):

    if not request.question.strip():
        raise HTTPException(
            status_code=400,
            detail="Question cannot be empty"
        )

    thread_id = request.threadId or str(uuid.uuid4())

    config = {
        "configurable": {
            "thread_id": thread_id
        },
        "metadata": {
            "thread_id": thread_id,
            "video_id": request.videoId
        },
        "run_name": "mern_ai_chat"
    }

    try:

        result = chatbot.invoke(
            {
                "messages": [
                    HumanMessage(
                        content=request.question.strip()
                    )
                ]
            },
            config=config
        )

        messages = result.get("messages", [])

        if not messages:
            raise HTTPException(
                status_code=500,
                detail="No response generated by AI"
            )

        final_message = messages[-1]

        return {
            "answer": final_message.content,
            "threadId": thread_id,
            "videoId": request.videoId
        }

    except Exception as e:

        print("========== AI ERROR ==========")
        print(str(e))
        print("==============================")

        raise HTTPException(
            status_code=500,
            detail="Failed to generate AI response"
        )


# =========================
# PDF Upload Endpoint
# =========================

@app.post("/upload-pdf")
async def upload_pdf(
    file: UploadFile = File(...),
    threadId: str = Form(...)
):

    if not file.filename:
        raise HTTPException(
            status_code=400,
            detail="PDF file is required"
        )

    if not file.filename.lower().endswith(".pdf"):
        raise HTTPException(
            status_code=400,
            detail="Only PDF files are allowed"
        )

    if not threadId.strip():
        raise HTTPException(
            status_code=400,
            detail="Thread ID is required"
        )

    try:

        print("========== PDF RECEIVED ==========")
        print("Filename:", file.filename)
        print("Thread ID:", threadId)

        # Read uploaded PDF into memory
        file_bytes = await file.read()

        if not file_bytes:
            raise HTTPException(
                status_code=400,
                detail="Uploaded PDF is empty"
            )

        # Send PDF to your existing RAG ingestion function
        result = ingest_pdf(
            file_bytes=file_bytes,
            thread_id=threadId,
            filename=file.filename
        )

        print("PDF indexed successfully")
        print("==================================")

        return {
            "success": True,
            "message": "PDF uploaded and indexed successfully",
            "threadId": threadId,
            "filename": result["filename"],
            "documents": result["documents"],
            "chunks": result["chunks"]
        }

    except HTTPException:
        raise

    except Exception as e:

        print("========== PDF ERROR ==========")
        print(str(e))
        print("===============================")

        raise HTTPException(
            status_code=500,
            detail=f"Failed to process PDF: {str(e)}"
        )